### ISSUE TITLE
Release a public docker image

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-etl#19]
~~make cumulus-etl pip installable.~~

We should release a public docker image for cumulus-etl. Currently folks have to grab the repo and build themselves. Let's reduce a little friction there.

We might still need to encourage that folks grab the repo, so that they have the compose.yaml file? Not sure how to make that easier. But baby steps.

Remember to update the setup docs too.

**Comment by mikix** [comment]
I talked with Matt about this - we are thinking it might not make sense to bother with a pip package. Cumulus ETL has a few hairy dependencies (MS tool which involves building a C# app, plus a couple docker images for cTAKES and cNLP) that are really quite awkward to get set up, which ruins some of the promise of "pip install and you're done"

Instead, we do want to push out a docker image (let's start with just pointing at `main` development tip) and continue to encourage the `docker compose` approach. This will make it pretty close to turnkey.

So I'm going to re-title this ticket to focus on pushing out a docker image. I think it's the same spirit (make a proper open source release easy to consume), just different implementation.

Andy, if you think that it'd still be good to release a pip package, let me know. I could be convinced easily (and it wouldn't be much work really - my concern is more on the value-of-it side rather than the effort side)

**Comment by mikix** [comment]
:tada: It's done! https://hub.docker.com/r/smartonfhir/cumulus-etl

Instructions updated as well.
