### ISSUE TITLE
ICD10 descriptions should by lazy loaded from static JSON map 

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-etl#235]
**Expected**: Bulk FHIR `Coding` _should_ contain "display" whenever a SYTEM+CODE is provided 
https://www.hl7.org/fhir/datatypes.html#Coding

**Actual:** 
The immediate issue is _i2b2 specific_, resulting in `cumulus-library` being responsible for mapping ICD10 code=display. 
https://github.com/smart-on-fhir/cumulus-etl/blob/main/cumulus_etl/loaders/i2b2/transform.py#L178

**Proposed Workaround**
1. export `cumulus-library` ICD10 mapping table as a JSON file with Key=code, Value=display 

2. When ETL runs, if a "display" is not provided for FHIR Condition then use the display from static JSON file 
https://github.com/smart-on-fhir/cumulus-library/tree/main/cumulus_library/studies/vocab

Note that 
* i2b2 is the only place where this is believed to an issue currently. 
* ICD10 is more than just FHIR Condition, can also apply to FHIR Procedures
* If more vocabs are needed, like CPT/SNOMED/RxNorm we should defer to UMLS ApiKey based lookups rather than trying to circulate UMLS ourselves.

**Comment by comorbidity** [comment]
Related to Library should support FHIR Condition in either SNOMED or ICD based system
https://github.com/smart-on-fhir/cumulus-library/issues/52

**Comment by comorbidity** [comment]
Could apply universally, not just i2b2 specific. 
Change to ETL should be very basic, could move this function to fhir_common for example 
https://github.com/smart-on-fhir/cumulus-etl/blob/main/cumulus_etl/loaders/i2b2/transform.py#L345

**Comment by dogversioning** [comment]
For posterity:
Our MVP approach is to assume, for the time being, that this will :only: apply to i2b2, and that we will have some language that says 'you must have a UMLS license'. We can optionally require a key and validate it in order to apply the display names?

We are assuming that a EHR system will supply valid coding/displays via bulk FHIR. In the event that a site does not, we should ask them to investigate feasibility of doing so. If for some reason it is not possible to do so, we will have to make a more complex solution of loading in mapping tables in the library, and requiring some kind of licensing for each coding system, and then :always: looking up code display names from these tables for core tables.

**Comment by dogversioning** [comment]
addressed via #238
